config/routes.rb
Rails.application.routes.draw do

  get "your" => 'user_blogs#your'
  resources :posts do
    resources :comments
  end

  resources :comments

  resources :user_blogs do
    resources :posts do
      resources :comments
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'posts#index'

  get 'home/authors'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment =  current_user.comments.build(post_id: params[:post_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment =  current_user.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:post_id, :title, :content, :date, :time)
    end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to post_path(id: @comment.post_id), notice: "You don't have permission to edit this post" if @comment.nil?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment, html: { multipart: true } do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :post_id, value: "#{params[:post_id]}" %>


  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= form.submit "Add", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Edit your comment</div>
  <div class="panel-body">

  <%= render 'form', comment: @comment %>


  </div>
  <div class="panel-footer"> <%= link_to 'Show', @comment %> |
    <%= link_to 'Back', comments_path %></div>
</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">Comments:</div>
<table class='table'>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>

        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


  <div class="panel-footer"><%= link_to 'New Comment',  new_post_comment_path %></div>
</div>

app/views/comments/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Create new comment</div>
  <div class="panel-body">
<%= render 'form', comment: @comment %>

  </div>
  <div class="panel-footer"><%= link_to 'Back', user_blog_post_path(id: @comment.post_id, user_blog_id: @comment.post.user_blog_id) %></div>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-body">
<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>





  </div>
  <div class="panel-footer">
    <% if @comment.user == current_user %>
      <%= link_to 'Edit', edit_comment_path(@comment) %>
    <%end %>

    <%= link_to 'Back', post_comment_path %>
  </div>
</div>