config/routes.rb
Rails.application.routes.draw do

  get "your" => 'user_blogs#your'
  resources :posts do
    resources :comments
  end

  resources :comments

  resources :user_blogs do
    resources :posts do
      resources :comments
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'posts#index'

  get 'home/authors'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def authors
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Blogowo', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Home', root_path%>
        </li>
        <li>
          <%= link_to 'Authors', home_authors_path%>
        </li>

        <li> <%= link_to 'Blogs', user_blogs_path %></li>

        <li> <%= link_to 'Posts', posts_path %></li>

        <%if user_signed_in? %>
          <li> <%= link_to 'New Blog', new_user_blog_path %></li>

          <li> <%= link_to 'Your blogs',  your_path %></li>

          <li> <%= link_to 'Edit profile', edit_user_registration_path %></li>

          <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>




        <% else %>

          <li> <%= link_to 'Sign in', new_user_session_path %></li>
          <li> <%= link_to 'Sign up', new_user_registration_path %></li>

        <% end %>
      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/authors.html.erb
<ul class="list-group">
  <h1><li class="list-group-item">Authors</li>
  <small>
  <li class="list-group-item">Weronika Żochowiec</li>
  <li class="list-group-item">Piotr Tomczyk</li>
  <li class="list-group-item">Michał Malesiński</li>
</small></h1>
</ul>