config/routes.rb
Rails.application.routes.draw do

  get "your" => 'user_blogs#your'
  resources :posts do
    resources :comments
  end

  resources :comments

  resources :user_blogs do
    resources :posts do
      resources :comments
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'posts#index'

  get 'home/authors'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_blog.rb
class UserBlog < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
end

app/controllers/user_blogs_controller.rb
class UserBlogsController < ApplicationController
  before_action :set_user_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /user_blogs
  # GET /user_blogs.json
  def index
    @user_blogs = UserBlog.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
  end

  def your
    @user_blogs = current_user.user_blogs.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
  end

  # GET /user_blogs/1
  # GET /user_blogs/1.json
  def show
    @user_blog = UserBlog.find(params[:id])
    @user= @user_blog.user
  end

  # GET /user_blogs/new
  def new
    @user_blog = current_user.user_blogs.build
  end


  # GET /user_blogs/1/edit
  def edit
  end

  # POST /user_blogs
  # POST /user_blogs.json
  def create
    @user_blog = current_user.user_blogs.build(user_blog_params)

    respond_to do |format|
      if @user_blog.save
        format.html { redirect_to @user_blog, notice: 'User blog was successfully created.' }
        format.json { render :show, status: :created, location: @user_blog }
      else
        format.html { render :new }
        format.json { render json: @user_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_blogs/1
  # PATCH/PUT /user_blogs/1.json
  def update
    respond_to do |format|
      if @user_blog.update(user_blog_params)
        format.html { redirect_to @user_blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_blog }
      else
        format.html { render :edit }
        format.json { render json: @user_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_blogs/1
  # DELETE /user_blogs/1.json
  def destroy
    @user_blog = UserBlog.find(params[:id])
    @post = @user_blog.posts.where(user_blog_id: @user_blog.id)
    @post.each do |post|
      @comment = post.comments.where(post_id: post.id)
      @comment.each do |comment|
        comment.destroy
      end
      post.destroy
    end
    @user_blog.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_blog
      @user_blog = UserBlog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_blog_params
      params.require(:user_blog).permit(:user_id, :name)
    end

  def correct_user
    @user_blog = current_user.user_blogs.find_by(id: params[:id])
    redirect_to root_path, notice: "You don't have permission to edit this blog" if @user_blog.nil?
  end
end

app/helpers/user_blogs_helper.rb
module UserBlogsHelper
end

app/views/user_blogs/_form.html.erb
<%= form_with(model: user_blog, local: true) do |form| %>
  <% if user_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_blog.errors.count, "error") %> prohibited this user_blog from being saved:</h2>

      <ul>
        <% user_blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control'  %>
  </div>

  <div class="actions">
    <%= form.submit 'submit',  class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/user_blogs/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Edit your blog</div>
  <div class="panel-body">

<%= render 'form', user_blog: @user_blog %>



  </div>
  <div class="panel-footer"> <%= link_to 'Show', @user_blog %> |
    <%= link_to 'Back', user_blogs_path %></div>
</div>

app/views/user_blogs/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Blogs:</div>
  <div class="panel-body">

      <% @user_blogs.each do |user_blog| %>

      <div class="panel panel-default">
        <div class="panel-body">

          <div class="page-header"><h3><%= link_to user_blog.name, user_blog_path(id: user_blog.id )%>
            <br/> <small> created by <%= user_blog.user.name %></small></h3></div>


          <% if user_blog.user == current_user %>
            <div class="btn-group" role="group" aria-label="...">
             <%= link_to 'Edit', edit_user_blog_path(user_blog),  class: 'btn btn-primary' %>
              <%= link_to 'Destroy', user_blog, method: :delete, data: { confirm: 'Are you sure?' },  class: 'btn btn-primary' %>
            </div>


          <% end %>
        </div>
      </div>

    <% end %>


<br>

</div>
</div>

<%= will_paginate @user_blogs %>

app/views/user_blogs/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Create new blog</div>
  <div class="panel-body">
<%= render 'form', user_blog: @user_blog %>


  </div>
  <div class="panel-footer"><%= link_to 'Back', user_blogs_path %></div>
</div>

app/views/user_blogs/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">


    <div class="page-header">
      <h1> <%= @user_blog.name %> <small>created by <%=@user_blog.user.name %></small></h1>
    </div>

    <% if @user_blog.user == current_user %>
      <%= link_to 'Change blog name', edit_user_blog_path(@user_blog),  class: 'btn btn-primary'%>
      <%= link_to 'New post', new_user_blog_post_path(@user_blog),  class: 'btn btn-primary'%>
    <%end %>


    <div class="container">

      <div id="posts" class="transitions-enabled">
    <% @user_blog.posts.each do |post| %>
          <div class="box">
            <div class="panel panel-default">
              <div class="panel-heading"><center><h3><%= link_to post.title, user_blog_post_path(user_blog_id: post.user_blog_id, id: post.id) %></h3></center></div> <br/>
              <div class="panel-body">
                <h5><%= post.created_at %> <br/></h5>
                <%= image_tag post.image.url(:thumb),:style => "border: 2px solid #2F3538" %> <br/>
              </div>
            </div>



      <% if @user_blog.user == current_user %>
            <div class="panel-footer">
              <div class="btn-group" role="group" aria-label="...">
                <%= link_to 'Edit', edit_user_blog_post_path(user_blog_id: post.user_blog_id, id: post.id), class: 'btn btn-primary' %>
                <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' },  class: 'btn btn-primary' %>
              </div>

            </div>
        <%end %>
          </div>
    <% end %>
      </div>
    </div>


  </div>
  <div class="panel-footer">


    <%= link_to 'Back', root_path,  class: 'btn btn-primary' %>
  </div>
</div>

app/views/user_blogs/your.html.erb
<div class="panel panel-default">
<div class="panel-heading">Blogs:</div>
<div class="panel-body">

  <% current_user.user_blogs.each do |user_blog| %>

    <div class="panel panel-default">
      <div class="panel-body">

        <div class="page-header"><h3><%= link_to user_blog.name, user_blog_path(id: user_blog.id )%> <br/> <small> created by <%= user_blog.user.name %></small></h3></div>


        <% if user_blog.user == current_user %>
          <div class="btn-group" role="group" aria-label="...">
             <%= link_to 'Edit', edit_user_blog_path(user_blog),  class: 'btn btn-primary' %>
            <%= link_to 'Destroy', user_blog, method: :delete, data: { confirm: 'Are you sure?' },  class: 'btn btn-primary' %>
          </div>


        <% end %>
      </div>
    </div>

  <% end %>


  <br>

</div>
</div>

<%= will_paginate @user_blogs %>